

      model.link_names = {
      'head','l_clav','l_farm','l_foot','l_hand','l_larm','l_lglut','l_lleg','l_scap','l_talus','l_uarm','l_uglut','l_uleg','ltorso','mtorso','pelvis','r_clav','r_farm','r_foot','r_hand','r_larm','r_lglut','r_lleg','r_scap','r_talus','r_uarm','r_uglut','r_uleg','utorso',
      } ;
      model.link_id = [
      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,
      ] ;
     model.link_map = containers.Map(model.link_names, model.link_id) ;

      
      
        model.parent(model.link_map('ltorso')) = model.link_map('pelvis') ;
        model.jtype{model.link_map('ltorso')} = axis_fcn([0 0 1]) ;
        model.Xtree{model.link_map('ltorso')} = xtree_fcn(...
            [-0.0125 0 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('mtorso')) = model.link_map('ltorso') ;
        model.jtype{model.link_map('mtorso')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('mtorso')} = xtree_fcn(...
            [0 0 0.14], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('utorso')) = model.link_map('mtorso') ;
        model.jtype{model.link_map('utorso')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('utorso')} = xtree_fcn(...
            [0 0 0.05], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_larm')) = model.link_map('l_uarm') ;
        model.jtype{model.link_map('l_larm')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('l_larm')} = xtree_fcn(...
            [0 0.121 0.013], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_uarm')) = model.link_map('l_scap') ;
        model.jtype{model.link_map('l_uarm')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('l_uarm')} = xtree_fcn(...
            [0 0.185 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_hand')) = model.link_map('l_farm') ;
        model.jtype{model.link_map('l_hand')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('l_hand')} = xtree_fcn(...
            [0 0.095 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_scap')) = model.link_map('l_clav') ;
        model.jtype{model.link_map('l_scap')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('l_scap')} = xtree_fcn(...
            [0 0.075 0.036], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_clav')) = model.link_map('utorso') ;
        model.jtype{model.link_map('l_clav')} = axis_fcn([0 -0.5 0.866025]) ;
        model.Xtree{model.link_map('l_clav')} = xtree_fcn(...
            [0.024 0.221 0.289], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_farm')) = model.link_map('l_larm') ;
        model.jtype{model.link_map('l_farm')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('l_farm')} = xtree_fcn(...
            [0 0.183 -0.013], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_lleg')) = model.link_map('l_uleg') ;
        model.jtype{model.link_map('l_lleg')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('l_lleg')} = xtree_fcn(...
            [-0.05 0 -0.374], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_foot')) = model.link_map('l_talus') ;
        model.jtype{model.link_map('l_foot')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('l_foot')} = xtree_fcn(...
            [0 0 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_uleg')) = model.link_map('l_lglut') ;
        model.jtype{model.link_map('l_uleg')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('l_uleg')} = xtree_fcn(...
            [0.05 0 -0.05], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_lglut')) = model.link_map('l_uglut') ;
        model.jtype{model.link_map('l_lglut')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('l_lglut')} = xtree_fcn(...
            [0 0 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_talus')) = model.link_map('l_lleg') ;
        model.jtype{model.link_map('l_talus')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('l_talus')} = xtree_fcn(...
            [0 0 -0.422], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('l_uglut')) = model.link_map('pelvis') ;
        model.jtype{model.link_map('l_uglut')} = axis_fcn([0 0 1]) ;
        model.Xtree{model.link_map('l_uglut')} = xtree_fcn(...
            [0 0.089 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('head')) = model.link_map('utorso') ;
        model.jtype{model.link_map('head')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('head')} = xtree_fcn(...
            [0.011 0 0.49], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_larm')) = model.link_map('r_uarm') ;
        model.jtype{model.link_map('r_larm')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('r_larm')} = xtree_fcn(...
            [0 -0.121 0.013], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_uarm')) = model.link_map('r_scap') ;
        model.jtype{model.link_map('r_uarm')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('r_uarm')} = xtree_fcn(...
            [0 -0.185 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_hand')) = model.link_map('r_farm') ;
        model.jtype{model.link_map('r_hand')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('r_hand')} = xtree_fcn(...
            [0 -0.095 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_scap')) = model.link_map('r_clav') ;
        model.jtype{model.link_map('r_scap')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('r_scap')} = xtree_fcn(...
            [0 -0.075 0.036], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_clav')) = model.link_map('utorso') ;
        model.jtype{model.link_map('r_clav')} = axis_fcn([0 0.5 0.866025]) ;
        model.Xtree{model.link_map('r_clav')} = xtree_fcn(...
            [0.024 -0.221 0.289], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_farm')) = model.link_map('r_larm') ;
        model.jtype{model.link_map('r_farm')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('r_farm')} = xtree_fcn(...
            [0 -0.183 -0.013], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_lleg')) = model.link_map('r_uleg') ;
        model.jtype{model.link_map('r_lleg')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('r_lleg')} = xtree_fcn(...
            [-0.05 0 -0.374], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_foot')) = model.link_map('r_talus') ;
        model.jtype{model.link_map('r_foot')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('r_foot')} = xtree_fcn(...
            [0 0 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_uleg')) = model.link_map('r_lglut') ;
        model.jtype{model.link_map('r_uleg')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('r_uleg')} = xtree_fcn(...
            [0.05 0 -0.05], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_lglut')) = model.link_map('r_uglut') ;
        model.jtype{model.link_map('r_lglut')} = axis_fcn([1 0 0]) ;
        model.Xtree{model.link_map('r_lglut')} = xtree_fcn(...
            [0 0 0], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_talus')) = model.link_map('r_lleg') ;
        model.jtype{model.link_map('r_talus')} = axis_fcn([0 1 0]) ;
        model.Xtree{model.link_map('r_talus')} = xtree_fcn(...
            [0 0 -0.422], ...
            [0 -0 0] ...
        ) ;
      
        model.parent(model.link_map('r_uglut')) = model.link_map('pelvis') ;
        model.jtype{model.link_map('r_uglut')} = axis_fcn([0 0 1]) ;
        model.Xtree{model.link_map('r_uglut')} = xtree_fcn(...
            [0 -0.089 0], ...
            [0 -0 0] ...
        ) ;
      
          model.I{1} = mcI_fcn(2.6, ...
              [-0.004 0 0.056], ...
              [0 -0 0], ...
              inertia_fcn(0.009, ...
                         0, ...
                         0, ...
                         0.006, ...
                         0, ...
                         0.007)) ;
        
          model.I{2} = mcI_fcn(2.369, ...
              [0.014 0.058 0.029], ...
              [0 -0 0], ...
              inertia_fcn(0.004, ...
                         0.001, ...
                         0, ...
                         0.006, ...
                         0, ...
                         0.007)) ;
        
          model.I{3} = mcI_fcn(0.981, ...
              [0 0.041 0], ...
              [0 -0 0], ...
              inertia_fcn(0.003, ...
                         0, ...
                         0, ...
                         0.001, ...
                         0, ...
                         0.003)) ;
        
          model.I{4} = mcI_fcn(1.634, ...
              [0.027 0 -0.067], ...
              [0 -0 0], ...
              inertia_fcn(0.002, ...
                         0, ...
                         0, ...
                         0.007, ...
                         0, ...
                         0.008)) ;
        
          model.I{5} = mcI_fcn(2.263, ...
              [0 0.093 0], ...
              [0 -0 0], ...
              inertia_fcn(0.01, ...
                         0, ...
                         0, ...
                         0.002, ...
                         0, ...
                         0.01)) ;
        
          model.I{6} = mcI_fcn(2.148, ...
              [-0.003 0.099 -0.014], ...
              [0 -0 0], ...
              inertia_fcn(0.005, ...
                         0, ...
                         0, ...
                         0.003, ...
                         0, ...
                         0.006)) ;
        
          model.I{7} = mcI_fcn(0.69, ...
              [0.0133341 0.0170484 -0.0312052], ...
              [0 -0 0], ...
              inertia_fcn(0.000691326, ...
                         -2.24344e-05, ...
                         2.50508e-06, ...
                         0.00126856, ...
                         0.000137862, ...
                         0.00106487)) ;
        
          model.I{8} = mcI_fcn(4.367, ...
              [0.001 0 -0.187], ...
              [0 -0 0], ...
              inertia_fcn(0.077, ...
                         0, ...
                         -0.003, ...
                         0.076, ...
                         0, ...
                         0.01)) ;
        
          model.I{9} = mcI_fcn(2.707, ...
              [-0.002 0.108 0], ...
              [0 -0 0], ...
              inertia_fcn(0.01, ...
                         0, ...
                         0, ...
                         0.005, ...
                         0, ...
                         0.013)) ;
        
          model.I{10} = mcI_fcn(0.1, ...
              [0 0 0], ...
              [0 -0 0], ...
              inertia_fcn(1.01674e-05, ...
                         0, ...
                         0, ...
                         8.42775e-06, ...
                         0, ...
                         1.30101e-05)) ;
        
          model.I{11} = mcI_fcn(1.881, ...
              [0.007 0.114 0.008], ...
              [0 -0 0], ...
              inertia_fcn(0.002, ...
                         0, ...
                         0, ...
                         0.003, ...
                         0, ...
                         0.003)) ;
        
          model.I{12} = mcI_fcn(0.5166, ...
              [0.00529262 -0.00344732 0.00313046], ...
              [0 -0 0], ...
              inertia_fcn(0.00074276, ...
                         -3.79607e-08, ...
                         -2.79549e-05, ...
                         0.000688179, ...
                         -3.2735e-08, ...
                         0.00041242)) ;
        
          model.I{13} = mcI_fcn(7.34, ...
              [0 0 -0.21], ...
              [0 -0 0], ...
              inertia_fcn(0.09, ...
                         0, ...
                         0, ...
                         0.09, ...
                         0, ...
                         0.02)) ;
        
          model.I{14} = mcI_fcn(1.92, ...
              [-0.0112984 -3.15366e-06 0.0746835], ...
              [0 -0 0], ...
              inertia_fcn(0.0039092, ...
                         -5.04491e-08, ...
                         -0.000342157, ...
                         0.00341694, ...
                         4.87119e-07, ...
                         0.00174492)) ;
        
          model.I{15} = mcI_fcn(0.55, ...
              [-0.00816266 -0.0131245 0.0305974], ...
              [0 -0 0], ...
              inertia_fcn(0.000454181, ...
                         -6.10764e-05, ...
                         3.94009e-05, ...
                         0.000483282, ...
                         5.27463e-05, ...
                         0.000444215)) ;
        
          model.I{16} = mcI_fcn(14.2529, ...
              [0.0111 0 0.0271], ...
              [0 -0 0], ...
              inertia_fcn(0.1244, ...
                         0.0008, ...
                         -0.0007, ...
                         0.0958, ...
                         -0.0005, ...
                         0.1167)) ;
        
          model.I{17} = mcI_fcn(2.369, ...
              [0.014 -0.058 0.029], ...
              [0 -0 0], ...
              inertia_fcn(0.004, ...
                         -0.001, ...
                         0, ...
                         0.006, ...
                         0, ...
                         0.007)) ;
        
          model.I{18} = mcI_fcn(0.981, ...
              [0 -0.041 0], ...
              [0 -0 0], ...
              inertia_fcn(0.003, ...
                         0, ...
                         0, ...
                         0.001, ...
                         0, ...
                         0.003)) ;
        
          model.I{19} = mcI_fcn(1.634, ...
              [0.027 0 -0.067], ...
              [0 -0 0], ...
              inertia_fcn(0.002, ...
                         0, ...
                         0, ...
                         0.007, ...
                         0, ...
                         0.008)) ;
        
          model.I{20} = mcI_fcn(2.263, ...
              [0 -0.093 0], ...
              [0 -0 0], ...
              inertia_fcn(0.01, ...
                         0, ...
                         0, ...
                         0.002, ...
                         0, ...
                         0.01)) ;
        
          model.I{21} = mcI_fcn(2.148, ...
              [-0.003 -0.099 -0.014], ...
              [0 -0 0], ...
              inertia_fcn(0.005, ...
                         0, ...
                         0, ...
                         0.003, ...
                         0, ...
                         0.006)) ;
        
          model.I{22} = mcI_fcn(0.69, ...
              [0.0133341 -0.0170484 -0.0312052], ...
              [0 -0 0], ...
              inertia_fcn(0.000691326, ...
                         2.24344e-05, ...
                         2.50508e-06, ...
                         0.00126856, ...
                         -0.000137862, ...
                         0.00106487)) ;
        
          model.I{23} = mcI_fcn(4.367, ...
              [0.001 0 -0.187], ...
              [0 -0 0], ...
              inertia_fcn(0.077, ...
                         -0, ...
                         -0.003, ...
                         0.076, ...
                         -0, ...
                         0.01)) ;
        
          model.I{24} = mcI_fcn(2.707, ...
              [-0.002 -0.108 0], ...
              [0 -0 0], ...
              inertia_fcn(0.01, ...
                         0, ...
                         0, ...
                         0.005, ...
                         0, ...
                         0.013)) ;
        
          model.I{25} = mcI_fcn(0.1, ...
              [0 0 0], ...
              [0 -0 0], ...
              inertia_fcn(1.01674e-05, ...
                         0, ...
                         0, ...
                         8.42775e-06, ...
                         0, ...
                         1.30101e-05)) ;
        
          model.I{26} = mcI_fcn(1.881, ...
              [0.007 -0.114 0.008], ...
              [0 -0 0], ...
              inertia_fcn(0.002, ...
                         0, ...
                         0, ...
                         0.003, ...
                         0, ...
                         0.003)) ;
        
          model.I{27} = mcI_fcn(0.5166, ...
              [0.00529262 0.00344732 0.00313046], ...
              [0 -0 0], ...
              inertia_fcn(0.00074276, ...
                         3.79607e-08, ...
                         -2.79549e-05, ...
                         0.000688179, ...
                         3.2735e-08, ...
                         0.00041242)) ;
        
          model.I{28} = mcI_fcn(7.34, ...
              [0 0 -0.21], ...
              [0 -0 0], ...
              inertia_fcn(0.09, ...
                         0, ...
                         0, ...
                         0.09, ...
                         0, ...
                         0.02)) ;
        
          model.I{29} = mcI_fcn(18.484, ...
              [0.02 -0.001 0.211], ...
              [0 -0 0], ...
              inertia_fcn(0.395, ...
                         0, ...
                         0.083, ...
                         1.089, ...
                         -0.003, ...
                         0.327)) ;
        
      
      
      model = update_model_breadth_first(model) ;
      model.NB = length(model.link_id) ;
      model.Xtree{1} = eye(6) ;
      model.jtype{1} = 'R' ;

