

      model.link_names = {
      'pelvis','left_pelvis_abduction','left_pelvis_rotation','left_hip','left_thigh','left_knee','left_shin','left_tarsus','left_toe','right_pelvis_abduction','right_pelvis_rotation','right_hip','right_thigh','right_knee','right_shin','right_tarsus','right_toe',
      } ;
      model.link_id = [
      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,
      ] ;
     model.link_map = containers.Map(model.link_names, model.link_id) ;

      
      
        model.parent(model.link_map('left_pelvis_abduction')) = model.link_map('pelvis') ;
        
        	model.jtype{model.link_map('left_pelvis_abduction')} = axis_fcn([0, 0, 0]) ;
        
        model.Xtree{model.link_map('left_pelvis_abduction')} = xtree_fcn(...
            [0.021 0.135 0], ...
            [0 1.57079632679 0] ...
        ) ;
      
        model.parent(model.link_map('left_pelvis_rotation')) = model.link_map('left_pelvis_abduction') ;
        
			model.jtype{model.link_map('left_pelvis_rotation')} = axis_fcn([1 0 0]) ;
		
        model.Xtree{model.link_map('left_pelvis_rotation')} = xtree_fcn(...
            [0 0 -0.07], ...
            [0 -1.57079632679 0] ...
        ) ;
      
        model.parent(model.link_map('left_hip')) = model.link_map('left_pelvis_rotation') ;
        
			model.jtype{model.link_map('left_hip')} = axis_fcn([-1 0 0]) ;
		
        model.Xtree{model.link_map('left_hip')} = xtree_fcn(...
            [0 0 -0.09], ...
            [0 1.57079632679 -1.57079632679] ...
        ) ;
      
        model.parent(model.link_map('left_thigh')) = model.link_map('left_hip') ;
        
			model.jtype{model.link_map('left_thigh')} = axis_fcn([0 0 1]) ;
		
        model.Xtree{model.link_map('left_thigh')} = xtree_fcn(...
            [0 0 0], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('left_knee')) = model.link_map('left_thigh') ;
        
			model.jtype{model.link_map('left_knee')} = axis_fcn([0 0 1]) ;
		
        model.Xtree{model.link_map('left_knee')} = xtree_fcn(...
            [0.12 0 0.0045], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('left_shin')) = model.link_map('left_knee') ;
        
        	model.jtype{model.link_map('left_shin')} = axis_fcn([0, 0, 0]) ;
        
        model.Xtree{model.link_map('left_shin')} = xtree_fcn(...
            [0.0607 0.0474 0], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('left_tarsus')) = model.link_map('left_shin') ;
        
			model.jtype{model.link_map('left_tarsus')} = axis_fcn([0 0 1]) ;
		
        model.Xtree{model.link_map('left_tarsus')} = xtree_fcn(...
            [0.4348 0.02 0], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('left_toe')) = model.link_map('left_tarsus') ;
        
			model.jtype{model.link_map('left_toe')} = axis_fcn([0 0 1]) ;
		
        model.Xtree{model.link_map('left_toe')} = xtree_fcn(...
            [0.408 -0.04 0], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('right_pelvis_abduction')) = model.link_map('pelvis') ;
        
        	model.jtype{model.link_map('right_pelvis_abduction')} = axis_fcn([0, 0, 0]) ;
        
        model.Xtree{model.link_map('right_pelvis_abduction')} = xtree_fcn(...
            [0.021 -0.135 0], ...
            [0 1.57079632679 0] ...
        ) ;
      
        model.parent(model.link_map('right_pelvis_rotation')) = model.link_map('right_pelvis_abduction') ;
        
			model.jtype{model.link_map('right_pelvis_rotation')} = axis_fcn([1 0 0]) ;
		
        model.Xtree{model.link_map('right_pelvis_rotation')} = xtree_fcn(...
            [0 0 -0.07], ...
            [0 -1.57079632679 0] ...
        ) ;
      
        model.parent(model.link_map('right_hip')) = model.link_map('right_pelvis_rotation') ;
        
			model.jtype{model.link_map('right_hip')} = axis_fcn([-1 0 0]) ;
		
        model.Xtree{model.link_map('right_hip')} = xtree_fcn(...
            [0 0 -0.09], ...
            [0 1.57079632679 -1.57079632679] ...
        ) ;
      
        model.parent(model.link_map('right_thigh')) = model.link_map('right_hip') ;
        
			model.jtype{model.link_map('right_thigh')} = axis_fcn([0 0 1]) ;
		
        model.Xtree{model.link_map('right_thigh')} = xtree_fcn(...
            [0 0 0], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('right_knee')) = model.link_map('right_thigh') ;
        
			model.jtype{model.link_map('right_knee')} = axis_fcn([0 0 1]) ;
		
        model.Xtree{model.link_map('right_knee')} = xtree_fcn(...
            [0.12 0 -0.0045], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('right_shin')) = model.link_map('right_knee') ;
        
        	model.jtype{model.link_map('right_shin')} = axis_fcn([0, 0, 0]) ;
        
        model.Xtree{model.link_map('right_shin')} = xtree_fcn(...
            [0.0607 0.0474 0], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('right_tarsus')) = model.link_map('right_shin') ;
        
			model.jtype{model.link_map('right_tarsus')} = axis_fcn([0 0 1]) ;
		
        model.Xtree{model.link_map('right_tarsus')} = xtree_fcn(...
            [0.4348 0.02 0], ...
            [0 0 0] ...
        ) ;
      
        model.parent(model.link_map('right_toe')) = model.link_map('right_tarsus') ;
        
			model.jtype{model.link_map('right_toe')} = axis_fcn([0 0 1]) ;
		
        model.Xtree{model.link_map('right_toe')} = xtree_fcn(...
            [0.408 -0.04 0], ...
            [0 0 0] ...
        ) ;
      
          model.I{1} = mcI_fcn(10.33, ...
              [.0507 0 .0284], ...
              [0 0 0], ...
              inertia_fcn(.0942, ...
                         .000169, ...
                         .015, ...
                         .084, ...
                         .000516, ...
                         .113)) ;
        
          model.I{2} = mcI_fcn(0, ...
              [0 0 0], ...
              [0 0 0], ...
              inertia_fcn(0, ...
                         0, ...
                         0, ...
                         0, ...
                         0, ...
                         0)) ;
        
          model.I{3} = mcI_fcn(1.82, ...
              [.0257 0.0001 .0179], ...
              [0 0 0], ...
              inertia_fcn(.00272, ...
                         7.03e-07, ...
                         .00000153, ...
                         .00559, ...
                         2.61e-06, ...
                         .004640)) ;
        
          model.I{4} = mcI_fcn(1.17, ...
              [-.0557 0 0], ...
              [0 0 0], ...
              inertia_fcn(.000842, ...
                         .000000246, ...
                         -.000000625, ...
                         .006080, ...
                         -.00000004, ...
                         .006440)) ;
        
          model.I{5} = mcI_fcn(5.52, ...
              [.0598 .0001 -0.0358], ...
              [0 0 0], ...
              inertia_fcn(.018, ...
                         .000284, ...
                         -0.0117, ...
                         .0563, ...
                         -1.93e-05, ...
                         .0498)) ;
        
          model.I{6} = mcI_fcn(.758, ...
              [.023 .0321 -0.0022], ...
              [0 0 0], ...
              inertia_fcn(.002160, ...
                         .000956, ...
                         2.84e-06, ...
                         .00144, ...
                         7.39e-07, ...
                         .00334)) ;
        
          model.I{7} = mcI_fcn(.577, ...
              [.1834 .0012 0.0002], ...
              [0 0 0], ...
              inertia_fcn(.000360, ...
                         .000334, ...
                         -1.94e-07, ...
                         .0341, ...
                         2.65e-07, ...
                         .0341)) ;
        
          model.I{8} = mcI_fcn(.782, ...
              [.1105 -.0306 -0.0013], ...
              [0 0 0], ...
              inertia_fcn(.00113, ...
                         -.00288, ...
                         -6.33e-05, ...
                         .0231, ...
                         3.62e-05, ...
                         .0239)) ;
        
          model.I{9} = mcI_fcn(.15, ...
              [.0047 .0275 -0.0001], ...
              [0 0 0], ...
              inertia_fcn(.000287, ...
                         -.0000986, ...
                         -1.46e-06, ...
                         .000171, ...
                         1.72e-07, ...
                         .000449)) ;
        
          model.I{10} = mcI_fcn(0, ...
              [0 0 0], ...
              [0 0 0], ...
              inertia_fcn(0, ...
                         0, ...
                         0, ...
                         0, ...
                         0, ...
                         0)) ;
        
          model.I{11} = mcI_fcn(1.82, ...
              [.0257 -0.0001 .0179], ...
              [0 0 0], ...
              inertia_fcn(.00272, ...
                         -7.03e-07, ...
                         .00000153, ...
                         .00559, ...
                         -2.61e-06, ...
                         .004640)) ;
        
          model.I{12} = mcI_fcn(1.17, ...
              [-.0557 0 0], ...
              [0 0 0], ...
              inertia_fcn(.000842, ...
                         .000000246, ...
                         -.000000625, ...
                         .006080, ...
                         -.00000004, ...
                         .006440)) ;
        
          model.I{13} = mcI_fcn(5.52, ...
              [.0598 .0001 0.0358], ...
              [0 0 0], ...
              inertia_fcn(.018, ...
                         .000284, ...
                         0.0117, ...
                         .0563, ...
                         1.93e-05, ...
                         .0498)) ;
        
          model.I{14} = mcI_fcn(.758, ...
              [.023 .0321 0.0022], ...
              [0 0 0], ...
              inertia_fcn(.002160, ...
                         .000956, ...
                         -2.84e-06, ...
                         .00144, ...
                         -7.39e-07, ...
                         .00334)) ;
        
          model.I{15} = mcI_fcn(.577, ...
              [.1834 .0012 -0.0002], ...
              [0 0 0], ...
              inertia_fcn(.000360, ...
                         .000334, ...
                         1.94e-07, ...
                         .0341, ...
                         -2.65e-07, ...
                         .0341)) ;
        
          model.I{16} = mcI_fcn(.782, ...
              [.1105 -.0306 0.0013], ...
              [0 0 0], ...
              inertia_fcn(.00113, ...
                         -.00288, ...
                         6.33e-05, ...
                         .0231, ...
                         -3.62e-05, ...
                         .0239)) ;
        
          model.I{17} = mcI_fcn(.15, ...
              [.0047 .0275 0.0001], ...
              [0 0 0], ...
              inertia_fcn(.000287, ...
                         -.0000986, ...
                         1.46e-06, ...
                         .000171, ...
                         -1.72e-07, ...
                         .000449)) ;
        
      
      
      model = update_model_breadth_first(model) ;
      model.NB = length(model.link_id) ;
      model.Xtree{1} = eye(6) ;
      model.jtype{1} = 'R' ;

